### ISSUE TITLE
程序闪退

### ISSUE THREAD

**Issue by char1eslu** [zhoury18/PvZHelper-Mac#4]
10.14.5, PvZ 1.0.40.   helper 1.3.2  
 打开程序后，输入密码，然后就闪退了

**Comment by zhoury18** [comment]
请尝试在终端中运行
sudo (所在路径)/PvZHelper.app/Contents/MacOS/PvZHelper
并输入密码，看看是否能打开...

**Comment by char1eslu** [comment]
dyld: Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Applications/PvZHelper.app/Contents/MacOS/PvZHelper
  Reason: image not found
[1]    3208 abort      sudo /Applications/PvZHelper.app/Contents/MacOS/PvZHelper

**Comment by zhoury18** [comment]
感谢反馈，请下载新的1.3.3版本尝试运行...

**Comment by char1eslu** [comment]
多谢更新，已可以打开
